### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by GunnarLieb** [Tropicalista/SuperSeo#2]
If I install from Foregebox for via Commandbox I get this error `invalid component definition, can't find component [modules.contentbox.modules_user.SuperSeo-1.2.0.ModuleConfig]
`

**Comment by GunnarLieb** [comment]
Don't know why but I have two modules
1. superseo 
2. superseo-1.2.0

after deleting 1.2.0 the modul installs fine

**Comment by GunnarLieb** [comment]
Ok, I tried first to install from Forgebox (Contentbox backend), which fails. So I think the superseo-1.2.0 came from this.

**Comment by Tropicalista** [comment]
I'm not very comfortable with forgebox api.  I was making some change to box.json and published changes.

**Comment by GunnarLieb** [comment]
I think there was a reference to a zip file named ....1.2.0 this is maybe the reason. I think it was in the box file
