### ISSUE TITLE
Messages: key [ANALYTICSVIEW] doesn't exist

### ISSUE THREAD

**Issue by GunnarLieb** [Tropicalista/SuperSeo#3]
/modules/contentbox/modules_user/SuperSeo/views/analytics/settings.cfm
LINE:	
`25: <select class="form-control" name="profile">
26: <cfloop array=#prc.profiles# index="profile">
27: <option value="#profile.id#" <cfif profile.id EQ prc.settings.analyticsView>selected</cfif>>#profile.name#</option>
28: </cfloop>
29: </select>`

**Comment by Tropicalista** [comment]
I have added default value in moduleconfig.
